### ISSUE TITLE
Image not convincing

### ISSUE THREAD

**Issue by ghost** [ThatTSGuy/discord-qr-token-grabber#2]
I dont like how the image comes out I tried to adjust the image myself but then I found a template online that I think you should copy for ur logger https://github.com/NightfallGT/Discord-QR-Scam/blob/main/temp/template.png?raw=true

**Comment by jack-temko** [comment]
I'll probably just make it pull the text from a JSON file so people can change it as they will. Would that work for you?

**Comment by ghost** [comment]
see the problem is the font and how it presents itself I don't think that will help out our case also I friended u on discord pls accept so we can talk more on the matter
