### ISSUE TITLE
skid

### ISSUE THREAD

**Issue by vividsec** [ThatTSGuy/discord-qr-token-grabber#5]
You're a huge skid, you are quite literally the definition of a skid you ape third worlder I hope Russia wins against Ukraine now because you're such an inconvenience in this world.

**Skid**

**Comment by jack-temko** [comment]
Go take your family issues elsewhere, little skid.

**Comment by vividsec** [comment]
you're a skid, keep crying.

**Comment by jack-temko** [comment]
Yikes dude. You clearly have some unresolved mental issues and/or childhood trauma. I hope you get the help you need. ♥️
